sudo: required

language: node_js
node_js:
	- "12.16.3"

before_script:
	- npm install -g @angular/cli

script:
	- npm run-script build

deploy:
	provider: pages
	skip_cleanup: true
	gitbub_token:  GITHUB_TOKEN
	on: 
		branch: master
